# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

parameters:
    public_dir: '%kernel.project_dir%/public'
    storage_dir: '%kernel.project_dir%/var'
    supported_languages: '%env(csv:SUPPORTED_LANGUAGES)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Service\ImageJobHandler:
        abstract: true

    # commands
    App\Command\ProcessImagesCommand:
        arguments:
            $projectDir: '%kernel.project_dir%'
            $workerLimit: '%env(int:WORKER_LIMIT)%'

    # games
    game.mtg.image_job_handler:
        parent: App\Service\ImageJobHandler
        arguments:
            $game: !php/enum App\Enum\Game::MagicTheGathering
            $urlResolver: '@App\Games\MTG\Service\CardImageUrlResolver'
        tags:
            - { name: 'api.image_job_handler', game: 'mtg' }

    game.pokemon.image_job_handler:
        parent: App\Service\ImageJobHandler
        arguments:
            $game: !php/enum App\Enum\Game::Pokemon
            $urlResolver: '@App\Games\Pokemon\Service\CardImageUrlResolver'
        tags:
            - { name: 'api.image_job_handler', game: 'pokemon' }

    game.lorcana.image_job_handler:
        parent: App\Service\ImageJobHandler
        arguments:
            $game: !php/enum App\Enum\Game::Lorcana
            $urlResolver: '@App\Games\Lorcana\Service\CardImageUrlResolver'
        tags:
            - { name: 'api.image_job_handler', game: 'lorcana' }
